### ISSUE TITLE
Use of capitals when overriding headers

### ISSUE THREAD

**Issue by pbruins84** [peiffer-innovations/rest_client#5]
rest_client adds the header `Content-Type: application/json` by default.

When you want to override this header, you have to specify the header in lowercase, like this:
```dart
Request(
      url: url,
      body: postBody,
      method: RequestMethod.post,
      headers: {'content-type': 'application/x-www-form-urlencoded'}
```
Then the header `Content-Type: application/x-www-form-urlencoded` will be added.(with `Content` and `Type` starting with uppercase letter)

But when you try this: (note the casing of `Content-Type`)
```dart
Request(
      url: url,
      body: postBody,
      method: RequestMethod.post,
      headers: {'Content-Type': 'application/x-www-form-urlencoded'}
```
Then the header in the final http request will stay like this: `Content-Type: application/json`

**Comment by jpeiffer** [comment]
Per HTTP specs, headers names (field names in the spec) are case-insensitive.
https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2

So I believe part of your assumption is incorrect.  The resulting case should not matter.  However, I just updated the library with `2.0.1+1` to lowercase all overrides first so that the library will identify `content-type` as having been passed in regardless of the case it was passed in as.
